#!/bin/sh

RC_CONF=/etc/rc.conf


if [ "X$2" == "XPRE-INSTALL" ]; then
    if ! /usr/sbin/pw groupshow krmx >/dev/null 2>&1; then
        /usr/sbin/pw groupadd krmx -g 5000
    fi

    if ! /usr/sbin/pw usershow krmx >/dev/null 2>&1; then
        /usr/sbin/pw useradd krmx -m -d /home/krmx \
         -u 5000 -g 5000 -c "Kronometrix user"
    fi
fi

if [ "X$2" == "XPOST-INSTALL" ]; then

    # setup crontabs
    if ! grep krmx /var/cron/allow >/dev/null 2>&1; then
        echo "krmx" >> /var/cron/allow
    fi

    if [ ! -f /var/cron/tabs/krmx ]; then
        echo "59 23 * * *  /bin/sleep 55 && /opt/kronometrix/mon/bin/raw2day -n && /usr/sbin/newsyslog -rf /etc/newsyslog.conf.d/kronometrix" >> /var/cron/tabs/krmx
        echo "00 00 * * *  /bin/sleep 15 && /opt/kronometrix/mon/bin/raw2day -c" >> /var/cron/tabs/krmx
    fi

    # newsyslog kronometrix log rotation job
    if [ ! -f /etc/newsyslog.conf.d/kronometrix ]; then
        cp /opt/kronometrix/mon/etc/kronometrix.newsyslog /etc/newsyslog.conf.d/kronometrix
    fi

    chown -R krmx:krmx /opt/kronometrix/mon

    # install kornometrix service
    grep "^kmon_enable" ${RC_CONF} >/dev/null 2>&1
    if [ $? -eq 1 ]; then

        # add the service
        echo "kmon_enable=\"YES\"" >> ${RC_CONF}
        if [ $? -eq 1 ]; then
            echo "Error: cannot activate service: kmon, exit now"
            exit 1
        fi
    fi

    grep "^kmon_user" ${RC_CONF} >/dev/null 2>&1 
    if [ $? -eq 1 ]; then
        echo "kmon_user=\"krmx\"" >> ${RC_CONF}
        if [ $? -eq 1 ]; then
            echo "Error: cannot activate service: kmon user, exit now"
            exit 1
        fi
    fi

    # start and link the service
    if [ ! -L /etc/rc.d/kmon ]; then
        ln -s /opt/kronometrix/mon/etc/rc/kmon /etc/rc.d/kmon
    fi

    /etc/rc.d/kmon onestart >/dev/null
fi
